### ISSUE TITLE
[BUG] DataSync Manager stops processing incoming WebHooks

### ISSUE THREAD

**Issue by idmedia-kaiser** [contentstack/datasync-manager#30]
**Describe the bug**
We are running DataSync in multiple environments (DEV, UAT, Production). All instances get there data from one stack via WebHooks. 
After some days the requests are no longer updating data. We can see in the logs that the request is still received, but not processed.

```
Request recived, 'POST : /notify'
Received 'contentstack sync' notification
```
We can also see that the last sync of an asset started but never finished

```
`Request recived, 'POST : /notify'
Received 'contentstack sync' notification
PUBLISH: { content_type: 'confirm_message', locale: 'de-de', uid: 'blt3363b5c134dc5895'} is in progress
item-logger before-sync logging: PUBLISH on blt3363b5c134dc5895 of confirm_message
item-logger after-sync logging: PUBLISH on blt3363b5c134dc5895 of confirm_message
PUBLISH: { content_type: 'confirm_message', locale: 'de-de', uid: 'blt3363b5c134dc5895'} was completed successfully!
```

```
Request recived, 'POST : /notify'
Received 'contentstack sync' notification
PUBLISH: { content_type: '_assets', locale: 'de-de', uid: 'blt1e440cb45eb5f406'} is in progress
item-logger before-sync logging: PUBLISH on blt1e440cb45eb5f406 of _assets
Request recived, 'POST : /notify'
Received 'contentstack sync' notification
Request recived, 'POST : /notify'
Received 'contentstack sync' notification
Request recived, 'POST : /notify'
Received 'contentstack sync' notification
Request recived, 'POST : /notify'
Received 'contentstack sync' notification
```
`
And after this there is only those 2 messages, but no sync. The sync process hung up after "item-logger before-sync logging: PUBLISH on blt1e440cb45eb5f406 of _assets"

This happend with the same asset at the same time for UAT / PROD

BUT, 30 mins earlier the same asset got published already and there it was successful

```
PUBLISH: { content_type: '_assets', locale: 'de-de', uid: 'blt1e440cb45eb5f406'} is in progress
item-logger before-sync logging: PUBLISH on blt1e440cb45eb5f406 of _assets
item-logger after-sync logging: PUBLISH on blt1e440cb45eb5f406 of _assets
PUBLISH: { content_type: '_assets', locale: 'de-de', uid: 'blt1e440cb45eb5f406'} was completed successfully!
```

**To Reproduce**
1.
Our project is based on  https://github.com/contentstack/datasync-boilerplate
Dependencies
"@contentstack/datasync-asset-store-filesystem": "2.0.1",
"@contentstack/datasync-content-store-filesystem": "2.0.2",
"@contentstack/datasync-manager": "2.0.1",
"@contentstack/webhook-listener": "1.0.0",
"contentstack": "3.15.0",
"datasync-filesystem-sdk": "file:./modules/datasync-filesystem-sdk-1.0.7.tgz",

2. Configuration info (except api_key/tokens) (Default config)
`import * as dotenv from "dotenv";
dotenv.config();

export const config = {
  // Make sure you have all the modules mentioned below installed
  contentStoreModule: '@contentstack/datasync-content-store-filesystem',
  assetStoreModule: '@contentstack/datasync-asset-store-filesystem',
  listenerModule: '@contentstack/webhook-listener',
  contentstack: {
       // Your stack's API key
       apiKey: process.env.CONTENTSTACK_API_KEY || "",
       // Your stack's environment based delivery token. (Goto Contentstack Dashboard -> Settings dropdown -> Tokens -> Generate tokens)
       deliveryToken: process.env.CONTENTSTACK_DELIVERY_TOKEN || "",
       environment: process.env.NODE_ENV || ""
  },
  plugins: [
    // Plugins starting with _cs_internal_ are app specific internal plugins
    // If you have custom plugins
    //  1. Create a 'plugins' folder in this app's directory
    //  2. Create a folder inside it
    //  3. Inside the folder, create a index.js file
    // Check example - plugins/dummy-plugin of this project
    
    {
      disabled: false,
      name: 'item-logger',
      options: {
        // Here, you can set your own custom logger
        log: console.log
      }
    },
    {
      disabled: false,
      // This plugin 
      //  - Modifies reference field structure of Stack's v3.4.x and below to new reference field structure (Array of uids, transformed to Array of objects)
      //  - Updates all old reference fields and makes them compatible with multiple references
      name: '_cs_internal_transform_entries',
      // path: '',
      options: {
        // other overrides...
      },
    },
    {
      disabled: false,
      // This plugin 
      //  - Detects asset/reference paths in a content type's schema
      //  - Updates all content types with asset/reference fields
      // Which can be later used with datasync-filesystem-sdk OR datasync-mongodb-sdk
      name: '_cs_internal_transform_schemas',
      options: {
        // Set false, if you do not wish to log asset references in the schema
        logAssetPaths: true,
        // Set false, if you do not wish to log entry references in the schema
        logReferencePaths: true,
      },
    },
    {
      disabled: false,
      // This plugin
      //  - Detects RTE/Markdown fields in a schema
      //  - Finds all the assets that's stored in Contentstack
      //  - Downloads all assets onto the asset store specified
      //  - Updates the entry's RTE/Markdown fields
      name: '_cs_internal_save_rte_markdown_assets',
      options: {
        // other overrides...
      },
    },
  ],
}
`

4. Content type schema & entry details / asset details (if possible)
Until now we only saw it fail with assets, but regardless of the asset itself

6. Copy paste the error in detail

**Expected behavior**
There should be an error thrown, if something is not syncing, but not just a hung process.

**Screenshots**
![image](https://user-images.githubusercontent.com/5065920/230319004-4f95223d-eb65-4077-aa41-0b8600927d57.png)

**Desktop (please complete the following information):**
Running inside kubernetes container

**Additional context**
This is a shop stopper for us to use DataSync in Production, as the sync is not reliable and can just stop updating data without some once noticing. It also doesn't help that we can't have something like  a healthstatus check, because the listener is still working.

**Comment by netrajpatel** [comment]
Hi @idmedia-kaiser,
This is strange behavior, but thanks for the detailed steps to reproduce.
We will investigate this issue and let you know.

**Comment by netrajpatel** [comment]
Hi @idmedia-kaiser,
The fix for this issue has been released already for the datasync-content-store-filesystem@2.0.3 and datasync-boilerplate@1.2.5 versions.
Hence closing this ticket.
